version: '3'

vars:
  VERSION: 0.4.0
  COMMIT:
    sh: git rev-parse --short HEAD

tasks:
  default:
    cmds:
      - task: mac_amd64
      - task: mac_arm64
      - task: windows
      - task: linux_amd64
      - task: linux_arm64
      - task: zip
  mac_amd64:
    cmds:
      - task: mkdir
      - GOOS=darwin GOARCH=amd64 go build -o dist/twlogeye.darwin_amd64 -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}" .
  mac_arm64:
    cmds:
      - task: mkdir
      - GOOS=darwin GOARCH=arm64 go build -o dist/twlogeye.darwin_arm64 -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}" .
  windows:
    cmds:
      - task: mkdir
      - GOOS=windows GOARCH=amd64 go build -o dist/twlogeye.exe -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}" .
  linux_amd64:
    cmds:
      - task: mkdir
      - GOOS=linux GOARCH=amd64 go build -o dist/twlogeye.linux_amd64 -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}" .
  linux_arm64:
    cmds:
      - task: mkdir
      - GOOS=linux GOARCH=arm64 go build -o dist/twlogeye.linux_arm64 -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}" .
  api:
    cmds:
      - (cd api;protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative twlogeye.proto)
  zip:
    cmds:
      - (cd dist;zip twlogeye.darwin.zip twlogeye.darwin*)
      - (cd dist;zip twlogeye.windows.zip twlogeye.exe)
      - (cd dist;zip twlogeye.linux.zip twlogeye.linux*) 
  mkdir:
    - mkdir -p dist
  clean:
    cmds:
      - rm -rf dist/*
  docker:
    cmds:
      - docker build -t twsnmp/twlogeye  --build-arg VERSION={{.VERSION}} --build-arg COMMIT={{.COMMIT}} .
