// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: twlogeye.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TWLogEyeService_Stop_FullMethodName                  = "/twlogeye.TWLogEyeService/Stop"
	TWLogEyeService_Reload_FullMethodName                = "/twlogeye.TWLogEyeService/Reload"
	TWLogEyeService_WatchNotify_FullMethodName           = "/twlogeye.TWLogEyeService/WatchNotify"
	TWLogEyeService_SearchNotify_FullMethodName          = "/twlogeye.TWLogEyeService/SearchNotify"
	TWLogEyeService_SearchLog_FullMethodName             = "/twlogeye.TWLogEyeService/SearchLog"
	TWLogEyeService_GetSyslogReport_FullMethodName       = "/twlogeye.TWLogEyeService/GetSyslogReport"
	TWLogEyeService_GetTrapReport_FullMethodName         = "/twlogeye.TWLogEyeService/GetTrapReport"
	TWLogEyeService_GetNetflowReport_FullMethodName      = "/twlogeye.TWLogEyeService/GetNetflowReport"
	TWLogEyeService_GetWindowsEventReport_FullMethodName = "/twlogeye.TWLogEyeService/GetWindowsEventReport"
)

// TWLogEyeServiceClient is the client API for TWLogEyeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TWLogEyeServiceClient interface {
	// Stop
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ControlResponse, error)
	// Reload sigma rules
	Reload(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ControlResponse, error)
	// Watch Notify
	WatchNotify(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyResponse], error)
	// Search Notify
	SearchNotify(ctx context.Context, in *NofifyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyResponse], error)
	// Search Log
	SearchLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogResponse], error)
	// Get Syslog Report
	GetSyslogReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyslogReportEnt], error)
	// Get Trap Report
	GetTrapReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrapReportEnt], error)
	// Get Netflow Report
	GetNetflowReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetFlowReportEnt], error)
	// Get Windows Event Report
	GetWindowsEventReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WindowsEventReportEnt], error)
}

type tWLogEyeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTWLogEyeServiceClient(cc grpc.ClientConnInterface) TWLogEyeServiceClient {
	return &tWLogEyeServiceClient{cc}
}

func (c *tWLogEyeServiceClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, TWLogEyeService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tWLogEyeServiceClient) Reload(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, TWLogEyeService_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tWLogEyeServiceClient) WatchNotify(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[0], TWLogEyeService_WatchNotify_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, NotifyResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_WatchNotifyClient = grpc.ServerStreamingClient[NotifyResponse]

func (c *tWLogEyeServiceClient) SearchNotify(ctx context.Context, in *NofifyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[1], TWLogEyeService_SearchNotify_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NofifyRequest, NotifyResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_SearchNotifyClient = grpc.ServerStreamingClient[NotifyResponse]

func (c *tWLogEyeServiceClient) SearchLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[2], TWLogEyeService_SearchLog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogRequest, LogResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_SearchLogClient = grpc.ServerStreamingClient[LogResponse]

func (c *tWLogEyeServiceClient) GetSyslogReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyslogReportEnt], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[3], TWLogEyeService_GetSyslogReport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReportRequest, SyslogReportEnt]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetSyslogReportClient = grpc.ServerStreamingClient[SyslogReportEnt]

func (c *tWLogEyeServiceClient) GetTrapReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrapReportEnt], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[4], TWLogEyeService_GetTrapReport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReportRequest, TrapReportEnt]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetTrapReportClient = grpc.ServerStreamingClient[TrapReportEnt]

func (c *tWLogEyeServiceClient) GetNetflowReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetFlowReportEnt], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[5], TWLogEyeService_GetNetflowReport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReportRequest, NetFlowReportEnt]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetNetflowReportClient = grpc.ServerStreamingClient[NetFlowReportEnt]

func (c *tWLogEyeServiceClient) GetWindowsEventReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WindowsEventReportEnt], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[6], TWLogEyeService_GetWindowsEventReport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReportRequest, WindowsEventReportEnt]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetWindowsEventReportClient = grpc.ServerStreamingClient[WindowsEventReportEnt]

// TWLogEyeServiceServer is the server API for TWLogEyeService service.
// All implementations must embed UnimplementedTWLogEyeServiceServer
// for forward compatibility.
type TWLogEyeServiceServer interface {
	// Stop
	Stop(context.Context, *Empty) (*ControlResponse, error)
	// Reload sigma rules
	Reload(context.Context, *Empty) (*ControlResponse, error)
	// Watch Notify
	WatchNotify(*Empty, grpc.ServerStreamingServer[NotifyResponse]) error
	// Search Notify
	SearchNotify(*NofifyRequest, grpc.ServerStreamingServer[NotifyResponse]) error
	// Search Log
	SearchLog(*LogRequest, grpc.ServerStreamingServer[LogResponse]) error
	// Get Syslog Report
	GetSyslogReport(*ReportRequest, grpc.ServerStreamingServer[SyslogReportEnt]) error
	// Get Trap Report
	GetTrapReport(*ReportRequest, grpc.ServerStreamingServer[TrapReportEnt]) error
	// Get Netflow Report
	GetNetflowReport(*ReportRequest, grpc.ServerStreamingServer[NetFlowReportEnt]) error
	// Get Windows Event Report
	GetWindowsEventReport(*ReportRequest, grpc.ServerStreamingServer[WindowsEventReportEnt]) error
	mustEmbedUnimplementedTWLogEyeServiceServer()
}

// UnimplementedTWLogEyeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTWLogEyeServiceServer struct{}

func (UnimplementedTWLogEyeServiceServer) Stop(context.Context, *Empty) (*ControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedTWLogEyeServiceServer) Reload(context.Context, *Empty) (*ControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedTWLogEyeServiceServer) WatchNotify(*Empty, grpc.ServerStreamingServer[NotifyResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WatchNotify not implemented")
}
func (UnimplementedTWLogEyeServiceServer) SearchNotify(*NofifyRequest, grpc.ServerStreamingServer[NotifyResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SearchNotify not implemented")
}
func (UnimplementedTWLogEyeServiceServer) SearchLog(*LogRequest, grpc.ServerStreamingServer[LogResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SearchLog not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetSyslogReport(*ReportRequest, grpc.ServerStreamingServer[SyslogReportEnt]) error {
	return status.Errorf(codes.Unimplemented, "method GetSyslogReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetTrapReport(*ReportRequest, grpc.ServerStreamingServer[TrapReportEnt]) error {
	return status.Errorf(codes.Unimplemented, "method GetTrapReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetNetflowReport(*ReportRequest, grpc.ServerStreamingServer[NetFlowReportEnt]) error {
	return status.Errorf(codes.Unimplemented, "method GetNetflowReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetWindowsEventReport(*ReportRequest, grpc.ServerStreamingServer[WindowsEventReportEnt]) error {
	return status.Errorf(codes.Unimplemented, "method GetWindowsEventReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) mustEmbedUnimplementedTWLogEyeServiceServer() {}
func (UnimplementedTWLogEyeServiceServer) testEmbeddedByValue()                         {}

// UnsafeTWLogEyeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TWLogEyeServiceServer will
// result in compilation errors.
type UnsafeTWLogEyeServiceServer interface {
	mustEmbedUnimplementedTWLogEyeServiceServer()
}

func RegisterTWLogEyeServiceServer(s grpc.ServiceRegistrar, srv TWLogEyeServiceServer) {
	// If the following call pancis, it indicates UnimplementedTWLogEyeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TWLogEyeService_ServiceDesc, srv)
}

func _TWLogEyeService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TWLogEyeServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TWLogEyeService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TWLogEyeServiceServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TWLogEyeService_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TWLogEyeServiceServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TWLogEyeService_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TWLogEyeServiceServer).Reload(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TWLogEyeService_WatchNotify_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).WatchNotify(m, &grpc.GenericServerStream[Empty, NotifyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_WatchNotifyServer = grpc.ServerStreamingServer[NotifyResponse]

func _TWLogEyeService_SearchNotify_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NofifyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).SearchNotify(m, &grpc.GenericServerStream[NofifyRequest, NotifyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_SearchNotifyServer = grpc.ServerStreamingServer[NotifyResponse]

func _TWLogEyeService_SearchLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).SearchLog(m, &grpc.GenericServerStream[LogRequest, LogResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_SearchLogServer = grpc.ServerStreamingServer[LogResponse]

func _TWLogEyeService_GetSyslogReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).GetSyslogReport(m, &grpc.GenericServerStream[ReportRequest, SyslogReportEnt]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetSyslogReportServer = grpc.ServerStreamingServer[SyslogReportEnt]

func _TWLogEyeService_GetTrapReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).GetTrapReport(m, &grpc.GenericServerStream[ReportRequest, TrapReportEnt]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetTrapReportServer = grpc.ServerStreamingServer[TrapReportEnt]

func _TWLogEyeService_GetNetflowReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).GetNetflowReport(m, &grpc.GenericServerStream[ReportRequest, NetFlowReportEnt]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetNetflowReportServer = grpc.ServerStreamingServer[NetFlowReportEnt]

func _TWLogEyeService_GetWindowsEventReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).GetWindowsEventReport(m, &grpc.GenericServerStream[ReportRequest, WindowsEventReportEnt]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetWindowsEventReportServer = grpc.ServerStreamingServer[WindowsEventReportEnt]

// TWLogEyeService_ServiceDesc is the grpc.ServiceDesc for TWLogEyeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TWLogEyeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "twlogeye.TWLogEyeService",
	HandlerType: (*TWLogEyeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stop",
			Handler:    _TWLogEyeService_Stop_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _TWLogEyeService_Reload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchNotify",
			Handler:       _TWLogEyeService_WatchNotify_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchNotify",
			Handler:       _TWLogEyeService_SearchNotify_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchLog",
			Handler:       _TWLogEyeService_SearchLog_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetSyslogReport",
			Handler:       _TWLogEyeService_GetSyslogReport_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTrapReport",
			Handler:       _TWLogEyeService_GetTrapReport_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetNetflowReport",
			Handler:       _TWLogEyeService_GetNetflowReport_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetWindowsEventReport",
			Handler:       _TWLogEyeService_GetWindowsEventReport_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "twlogeye.proto",
}
