// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: twlogeye.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TWLogEyeService_Stop_FullMethodName                      = "/twlogeye.TWLogEyeService/Stop"
	TWLogEyeService_Reload_FullMethodName                    = "/twlogeye.TWLogEyeService/Reload"
	TWLogEyeService_ClearDB_FullMethodName                   = "/twlogeye.TWLogEyeService/ClearDB"
	TWLogEyeService_WatchNotify_FullMethodName               = "/twlogeye.TWLogEyeService/WatchNotify"
	TWLogEyeService_SearchNotify_FullMethodName              = "/twlogeye.TWLogEyeService/SearchNotify"
	TWLogEyeService_SearchLog_FullMethodName                 = "/twlogeye.TWLogEyeService/SearchLog"
	TWLogEyeService_GetSyslogReport_FullMethodName           = "/twlogeye.TWLogEyeService/GetSyslogReport"
	TWLogEyeService_GetLastSyslogReport_FullMethodName       = "/twlogeye.TWLogEyeService/GetLastSyslogReport"
	TWLogEyeService_GetTrapReport_FullMethodName             = "/twlogeye.TWLogEyeService/GetTrapReport"
	TWLogEyeService_GetLastTrapReport_FullMethodName         = "/twlogeye.TWLogEyeService/GetLastTrapReport"
	TWLogEyeService_GetNetflowReport_FullMethodName          = "/twlogeye.TWLogEyeService/GetNetflowReport"
	TWLogEyeService_GetLastNetflowReport_FullMethodName      = "/twlogeye.TWLogEyeService/GetLastNetflowReport"
	TWLogEyeService_GetWindowsEventReport_FullMethodName     = "/twlogeye.TWLogEyeService/GetWindowsEventReport"
	TWLogEyeService_GetLastWindowsEventReport_FullMethodName = "/twlogeye.TWLogEyeService/GetLastWindowsEventReport"
	TWLogEyeService_GetOTelReport_FullMethodName             = "/twlogeye.TWLogEyeService/GetOTelReport"
	TWLogEyeService_GetLastOTelReport_FullMethodName         = "/twlogeye.TWLogEyeService/GetLastOTelReport"
	TWLogEyeService_GetAnomalyReport_FullMethodName          = "/twlogeye.TWLogEyeService/GetAnomalyReport"
	TWLogEyeService_GetLastAnomalyReport_FullMethodName      = "/twlogeye.TWLogEyeService/GetLastAnomalyReport"
	TWLogEyeService_GetMonitorReport_FullMethodName          = "/twlogeye.TWLogEyeService/GetMonitorReport"
	TWLogEyeService_GetLastMonitorReport_FullMethodName      = "/twlogeye.TWLogEyeService/GetLastMonitorReport"
	TWLogEyeService_GetOTelMetricList_FullMethodName         = "/twlogeye.TWLogEyeService/GetOTelMetricList"
	TWLogEyeService_GetOTelMetric_FullMethodName             = "/twlogeye.TWLogEyeService/GetOTelMetric"
	TWLogEyeService_GetOTelTraceList_FullMethodName          = "/twlogeye.TWLogEyeService/GetOTelTraceList"
	TWLogEyeService_GetOTelTrace_FullMethodName              = "/twlogeye.TWLogEyeService/GetOTelTrace"
)

// TWLogEyeServiceClient is the client API for TWLogEyeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TWLogEyeServiceClient interface {
	// Stop
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ControlResponse, error)
	// Reload sigma rules
	Reload(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ControlResponse, error)
	// ClearDB
	ClearDB(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	// Watch Notify
	WatchNotify(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyResponse], error)
	// Search Notify
	SearchNotify(ctx context.Context, in *NofifyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyResponse], error)
	// Search Log
	SearchLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogResponse], error)
	// Get Syslog Report
	GetSyslogReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyslogReportEnt], error)
	// Get Last Syslog Report
	GetLastSyslogReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SyslogReportEnt, error)
	// Get Trap Report
	GetTrapReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrapReportEnt], error)
	// Get Last Trap Report
	GetLastTrapReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TrapReportEnt, error)
	// Get Netflow Report
	GetNetflowReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetflowReportEnt], error)
	// Get Last Netflow Report
	GetLastNetflowReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetflowReportEnt, error)
	// Get Windows Event Report
	GetWindowsEventReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WindowsEventReportEnt], error)
	// Get Last Windows Event Report
	GetLastWindowsEventReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WindowsEventReportEnt, error)
	// Get OpenTelemetry Report
	GetOTelReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OTelReportEnt], error)
	// Get Last OpenTelemetry Report
	GetLastOTelReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OTelReportEnt, error)
	// Get Anomaly Report
	GetAnomalyReport(ctx context.Context, in *AnomalyReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnomalyReportEnt], error)
	// Get Last Anomaly Report
	GetLastAnomalyReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LastAnomalyReportEnt, error)
	// Get Monitor Report
	GetMonitorReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MonitorReportEnt], error)
	// Get Last Monitor Report
	GetLastMonitorReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MonitorReportEnt, error)
	// Get OpenTelemetry Metric List
	GetOTelMetricList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OTelMetricListEnt], error)
	// Get OpenTelemetry Metric
	GetOTelMetric(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*OTelMetricEnt, error)
	// Get OpenTelemetry Trace List
	GetOTelTraceList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OTelTraceListEnt], error)
	// Get OpenTelemetry Trace
	GetOTelTrace(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*OTelTraceEnt, error)
}

type tWLogEyeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTWLogEyeServiceClient(cc grpc.ClientConnInterface) TWLogEyeServiceClient {
	return &tWLogEyeServiceClient{cc}
}

func (c *tWLogEyeServiceClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, TWLogEyeService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tWLogEyeServiceClient) Reload(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, TWLogEyeService_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tWLogEyeServiceClient) ClearDB(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, TWLogEyeService_ClearDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tWLogEyeServiceClient) WatchNotify(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[0], TWLogEyeService_WatchNotify_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, NotifyResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_WatchNotifyClient = grpc.ServerStreamingClient[NotifyResponse]

func (c *tWLogEyeServiceClient) SearchNotify(ctx context.Context, in *NofifyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[1], TWLogEyeService_SearchNotify_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NofifyRequest, NotifyResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_SearchNotifyClient = grpc.ServerStreamingClient[NotifyResponse]

func (c *tWLogEyeServiceClient) SearchLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[2], TWLogEyeService_SearchLog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogRequest, LogResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_SearchLogClient = grpc.ServerStreamingClient[LogResponse]

func (c *tWLogEyeServiceClient) GetSyslogReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyslogReportEnt], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[3], TWLogEyeService_GetSyslogReport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReportRequest, SyslogReportEnt]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetSyslogReportClient = grpc.ServerStreamingClient[SyslogReportEnt]

func (c *tWLogEyeServiceClient) GetLastSyslogReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SyslogReportEnt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyslogReportEnt)
	err := c.cc.Invoke(ctx, TWLogEyeService_GetLastSyslogReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tWLogEyeServiceClient) GetTrapReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrapReportEnt], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[4], TWLogEyeService_GetTrapReport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReportRequest, TrapReportEnt]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetTrapReportClient = grpc.ServerStreamingClient[TrapReportEnt]

func (c *tWLogEyeServiceClient) GetLastTrapReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TrapReportEnt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrapReportEnt)
	err := c.cc.Invoke(ctx, TWLogEyeService_GetLastTrapReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tWLogEyeServiceClient) GetNetflowReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetflowReportEnt], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[5], TWLogEyeService_GetNetflowReport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReportRequest, NetflowReportEnt]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetNetflowReportClient = grpc.ServerStreamingClient[NetflowReportEnt]

func (c *tWLogEyeServiceClient) GetLastNetflowReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetflowReportEnt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetflowReportEnt)
	err := c.cc.Invoke(ctx, TWLogEyeService_GetLastNetflowReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tWLogEyeServiceClient) GetWindowsEventReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WindowsEventReportEnt], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[6], TWLogEyeService_GetWindowsEventReport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReportRequest, WindowsEventReportEnt]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetWindowsEventReportClient = grpc.ServerStreamingClient[WindowsEventReportEnt]

func (c *tWLogEyeServiceClient) GetLastWindowsEventReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WindowsEventReportEnt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WindowsEventReportEnt)
	err := c.cc.Invoke(ctx, TWLogEyeService_GetLastWindowsEventReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tWLogEyeServiceClient) GetOTelReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OTelReportEnt], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[7], TWLogEyeService_GetOTelReport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReportRequest, OTelReportEnt]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetOTelReportClient = grpc.ServerStreamingClient[OTelReportEnt]

func (c *tWLogEyeServiceClient) GetLastOTelReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OTelReportEnt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OTelReportEnt)
	err := c.cc.Invoke(ctx, TWLogEyeService_GetLastOTelReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tWLogEyeServiceClient) GetAnomalyReport(ctx context.Context, in *AnomalyReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnomalyReportEnt], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[8], TWLogEyeService_GetAnomalyReport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnomalyReportRequest, AnomalyReportEnt]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetAnomalyReportClient = grpc.ServerStreamingClient[AnomalyReportEnt]

func (c *tWLogEyeServiceClient) GetLastAnomalyReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LastAnomalyReportEnt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LastAnomalyReportEnt)
	err := c.cc.Invoke(ctx, TWLogEyeService_GetLastAnomalyReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tWLogEyeServiceClient) GetMonitorReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MonitorReportEnt], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[9], TWLogEyeService_GetMonitorReport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReportRequest, MonitorReportEnt]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetMonitorReportClient = grpc.ServerStreamingClient[MonitorReportEnt]

func (c *tWLogEyeServiceClient) GetLastMonitorReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MonitorReportEnt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorReportEnt)
	err := c.cc.Invoke(ctx, TWLogEyeService_GetLastMonitorReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tWLogEyeServiceClient) GetOTelMetricList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OTelMetricListEnt], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[10], TWLogEyeService_GetOTelMetricList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, OTelMetricListEnt]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetOTelMetricListClient = grpc.ServerStreamingClient[OTelMetricListEnt]

func (c *tWLogEyeServiceClient) GetOTelMetric(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*OTelMetricEnt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OTelMetricEnt)
	err := c.cc.Invoke(ctx, TWLogEyeService_GetOTelMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tWLogEyeServiceClient) GetOTelTraceList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OTelTraceListEnt], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TWLogEyeService_ServiceDesc.Streams[11], TWLogEyeService_GetOTelTraceList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, OTelTraceListEnt]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetOTelTraceListClient = grpc.ServerStreamingClient[OTelTraceListEnt]

func (c *tWLogEyeServiceClient) GetOTelTrace(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*OTelTraceEnt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OTelTraceEnt)
	err := c.cc.Invoke(ctx, TWLogEyeService_GetOTelTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TWLogEyeServiceServer is the server API for TWLogEyeService service.
// All implementations must embed UnimplementedTWLogEyeServiceServer
// for forward compatibility.
type TWLogEyeServiceServer interface {
	// Stop
	Stop(context.Context, *Empty) (*ControlResponse, error)
	// Reload sigma rules
	Reload(context.Context, *Empty) (*ControlResponse, error)
	// ClearDB
	ClearDB(context.Context, *ClearRequest) (*ControlResponse, error)
	// Watch Notify
	WatchNotify(*Empty, grpc.ServerStreamingServer[NotifyResponse]) error
	// Search Notify
	SearchNotify(*NofifyRequest, grpc.ServerStreamingServer[NotifyResponse]) error
	// Search Log
	SearchLog(*LogRequest, grpc.ServerStreamingServer[LogResponse]) error
	// Get Syslog Report
	GetSyslogReport(*ReportRequest, grpc.ServerStreamingServer[SyslogReportEnt]) error
	// Get Last Syslog Report
	GetLastSyslogReport(context.Context, *Empty) (*SyslogReportEnt, error)
	// Get Trap Report
	GetTrapReport(*ReportRequest, grpc.ServerStreamingServer[TrapReportEnt]) error
	// Get Last Trap Report
	GetLastTrapReport(context.Context, *Empty) (*TrapReportEnt, error)
	// Get Netflow Report
	GetNetflowReport(*ReportRequest, grpc.ServerStreamingServer[NetflowReportEnt]) error
	// Get Last Netflow Report
	GetLastNetflowReport(context.Context, *Empty) (*NetflowReportEnt, error)
	// Get Windows Event Report
	GetWindowsEventReport(*ReportRequest, grpc.ServerStreamingServer[WindowsEventReportEnt]) error
	// Get Last Windows Event Report
	GetLastWindowsEventReport(context.Context, *Empty) (*WindowsEventReportEnt, error)
	// Get OpenTelemetry Report
	GetOTelReport(*ReportRequest, grpc.ServerStreamingServer[OTelReportEnt]) error
	// Get Last OpenTelemetry Report
	GetLastOTelReport(context.Context, *Empty) (*OTelReportEnt, error)
	// Get Anomaly Report
	GetAnomalyReport(*AnomalyReportRequest, grpc.ServerStreamingServer[AnomalyReportEnt]) error
	// Get Last Anomaly Report
	GetLastAnomalyReport(context.Context, *Empty) (*LastAnomalyReportEnt, error)
	// Get Monitor Report
	GetMonitorReport(*ReportRequest, grpc.ServerStreamingServer[MonitorReportEnt]) error
	// Get Last Monitor Report
	GetLastMonitorReport(context.Context, *Empty) (*MonitorReportEnt, error)
	// Get OpenTelemetry Metric List
	GetOTelMetricList(*Empty, grpc.ServerStreamingServer[OTelMetricListEnt]) error
	// Get OpenTelemetry Metric
	GetOTelMetric(context.Context, *IDRequest) (*OTelMetricEnt, error)
	// Get OpenTelemetry Trace List
	GetOTelTraceList(*Empty, grpc.ServerStreamingServer[OTelTraceListEnt]) error
	// Get OpenTelemetry Trace
	GetOTelTrace(context.Context, *IDRequest) (*OTelTraceEnt, error)
	mustEmbedUnimplementedTWLogEyeServiceServer()
}

// UnimplementedTWLogEyeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTWLogEyeServiceServer struct{}

func (UnimplementedTWLogEyeServiceServer) Stop(context.Context, *Empty) (*ControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedTWLogEyeServiceServer) Reload(context.Context, *Empty) (*ControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedTWLogEyeServiceServer) ClearDB(context.Context, *ClearRequest) (*ControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearDB not implemented")
}
func (UnimplementedTWLogEyeServiceServer) WatchNotify(*Empty, grpc.ServerStreamingServer[NotifyResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WatchNotify not implemented")
}
func (UnimplementedTWLogEyeServiceServer) SearchNotify(*NofifyRequest, grpc.ServerStreamingServer[NotifyResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SearchNotify not implemented")
}
func (UnimplementedTWLogEyeServiceServer) SearchLog(*LogRequest, grpc.ServerStreamingServer[LogResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SearchLog not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetSyslogReport(*ReportRequest, grpc.ServerStreamingServer[SyslogReportEnt]) error {
	return status.Errorf(codes.Unimplemented, "method GetSyslogReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetLastSyslogReport(context.Context, *Empty) (*SyslogReportEnt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastSyslogReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetTrapReport(*ReportRequest, grpc.ServerStreamingServer[TrapReportEnt]) error {
	return status.Errorf(codes.Unimplemented, "method GetTrapReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetLastTrapReport(context.Context, *Empty) (*TrapReportEnt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastTrapReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetNetflowReport(*ReportRequest, grpc.ServerStreamingServer[NetflowReportEnt]) error {
	return status.Errorf(codes.Unimplemented, "method GetNetflowReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetLastNetflowReport(context.Context, *Empty) (*NetflowReportEnt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastNetflowReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetWindowsEventReport(*ReportRequest, grpc.ServerStreamingServer[WindowsEventReportEnt]) error {
	return status.Errorf(codes.Unimplemented, "method GetWindowsEventReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetLastWindowsEventReport(context.Context, *Empty) (*WindowsEventReportEnt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastWindowsEventReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetOTelReport(*ReportRequest, grpc.ServerStreamingServer[OTelReportEnt]) error {
	return status.Errorf(codes.Unimplemented, "method GetOTelReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetLastOTelReport(context.Context, *Empty) (*OTelReportEnt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastOTelReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetAnomalyReport(*AnomalyReportRequest, grpc.ServerStreamingServer[AnomalyReportEnt]) error {
	return status.Errorf(codes.Unimplemented, "method GetAnomalyReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetLastAnomalyReport(context.Context, *Empty) (*LastAnomalyReportEnt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastAnomalyReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetMonitorReport(*ReportRequest, grpc.ServerStreamingServer[MonitorReportEnt]) error {
	return status.Errorf(codes.Unimplemented, "method GetMonitorReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetLastMonitorReport(context.Context, *Empty) (*MonitorReportEnt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastMonitorReport not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetOTelMetricList(*Empty, grpc.ServerStreamingServer[OTelMetricListEnt]) error {
	return status.Errorf(codes.Unimplemented, "method GetOTelMetricList not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetOTelMetric(context.Context, *IDRequest) (*OTelMetricEnt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOTelMetric not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetOTelTraceList(*Empty, grpc.ServerStreamingServer[OTelTraceListEnt]) error {
	return status.Errorf(codes.Unimplemented, "method GetOTelTraceList not implemented")
}
func (UnimplementedTWLogEyeServiceServer) GetOTelTrace(context.Context, *IDRequest) (*OTelTraceEnt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOTelTrace not implemented")
}
func (UnimplementedTWLogEyeServiceServer) mustEmbedUnimplementedTWLogEyeServiceServer() {}
func (UnimplementedTWLogEyeServiceServer) testEmbeddedByValue()                         {}

// UnsafeTWLogEyeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TWLogEyeServiceServer will
// result in compilation errors.
type UnsafeTWLogEyeServiceServer interface {
	mustEmbedUnimplementedTWLogEyeServiceServer()
}

func RegisterTWLogEyeServiceServer(s grpc.ServiceRegistrar, srv TWLogEyeServiceServer) {
	// If the following call pancis, it indicates UnimplementedTWLogEyeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TWLogEyeService_ServiceDesc, srv)
}

func _TWLogEyeService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TWLogEyeServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TWLogEyeService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TWLogEyeServiceServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TWLogEyeService_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TWLogEyeServiceServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TWLogEyeService_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TWLogEyeServiceServer).Reload(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TWLogEyeService_ClearDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TWLogEyeServiceServer).ClearDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TWLogEyeService_ClearDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TWLogEyeServiceServer).ClearDB(ctx, req.(*ClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TWLogEyeService_WatchNotify_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).WatchNotify(m, &grpc.GenericServerStream[Empty, NotifyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_WatchNotifyServer = grpc.ServerStreamingServer[NotifyResponse]

func _TWLogEyeService_SearchNotify_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NofifyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).SearchNotify(m, &grpc.GenericServerStream[NofifyRequest, NotifyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_SearchNotifyServer = grpc.ServerStreamingServer[NotifyResponse]

func _TWLogEyeService_SearchLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).SearchLog(m, &grpc.GenericServerStream[LogRequest, LogResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_SearchLogServer = grpc.ServerStreamingServer[LogResponse]

func _TWLogEyeService_GetSyslogReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).GetSyslogReport(m, &grpc.GenericServerStream[ReportRequest, SyslogReportEnt]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetSyslogReportServer = grpc.ServerStreamingServer[SyslogReportEnt]

func _TWLogEyeService_GetLastSyslogReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TWLogEyeServiceServer).GetLastSyslogReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TWLogEyeService_GetLastSyslogReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TWLogEyeServiceServer).GetLastSyslogReport(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TWLogEyeService_GetTrapReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).GetTrapReport(m, &grpc.GenericServerStream[ReportRequest, TrapReportEnt]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetTrapReportServer = grpc.ServerStreamingServer[TrapReportEnt]

func _TWLogEyeService_GetLastTrapReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TWLogEyeServiceServer).GetLastTrapReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TWLogEyeService_GetLastTrapReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TWLogEyeServiceServer).GetLastTrapReport(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TWLogEyeService_GetNetflowReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).GetNetflowReport(m, &grpc.GenericServerStream[ReportRequest, NetflowReportEnt]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetNetflowReportServer = grpc.ServerStreamingServer[NetflowReportEnt]

func _TWLogEyeService_GetLastNetflowReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TWLogEyeServiceServer).GetLastNetflowReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TWLogEyeService_GetLastNetflowReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TWLogEyeServiceServer).GetLastNetflowReport(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TWLogEyeService_GetWindowsEventReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).GetWindowsEventReport(m, &grpc.GenericServerStream[ReportRequest, WindowsEventReportEnt]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetWindowsEventReportServer = grpc.ServerStreamingServer[WindowsEventReportEnt]

func _TWLogEyeService_GetLastWindowsEventReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TWLogEyeServiceServer).GetLastWindowsEventReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TWLogEyeService_GetLastWindowsEventReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TWLogEyeServiceServer).GetLastWindowsEventReport(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TWLogEyeService_GetOTelReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).GetOTelReport(m, &grpc.GenericServerStream[ReportRequest, OTelReportEnt]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetOTelReportServer = grpc.ServerStreamingServer[OTelReportEnt]

func _TWLogEyeService_GetLastOTelReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TWLogEyeServiceServer).GetLastOTelReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TWLogEyeService_GetLastOTelReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TWLogEyeServiceServer).GetLastOTelReport(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TWLogEyeService_GetAnomalyReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnomalyReportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).GetAnomalyReport(m, &grpc.GenericServerStream[AnomalyReportRequest, AnomalyReportEnt]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetAnomalyReportServer = grpc.ServerStreamingServer[AnomalyReportEnt]

func _TWLogEyeService_GetLastAnomalyReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TWLogEyeServiceServer).GetLastAnomalyReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TWLogEyeService_GetLastAnomalyReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TWLogEyeServiceServer).GetLastAnomalyReport(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TWLogEyeService_GetMonitorReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).GetMonitorReport(m, &grpc.GenericServerStream[ReportRequest, MonitorReportEnt]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetMonitorReportServer = grpc.ServerStreamingServer[MonitorReportEnt]

func _TWLogEyeService_GetLastMonitorReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TWLogEyeServiceServer).GetLastMonitorReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TWLogEyeService_GetLastMonitorReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TWLogEyeServiceServer).GetLastMonitorReport(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TWLogEyeService_GetOTelMetricList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).GetOTelMetricList(m, &grpc.GenericServerStream[Empty, OTelMetricListEnt]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetOTelMetricListServer = grpc.ServerStreamingServer[OTelMetricListEnt]

func _TWLogEyeService_GetOTelMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TWLogEyeServiceServer).GetOTelMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TWLogEyeService_GetOTelMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TWLogEyeServiceServer).GetOTelMetric(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TWLogEyeService_GetOTelTraceList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TWLogEyeServiceServer).GetOTelTraceList(m, &grpc.GenericServerStream[Empty, OTelTraceListEnt]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TWLogEyeService_GetOTelTraceListServer = grpc.ServerStreamingServer[OTelTraceListEnt]

func _TWLogEyeService_GetOTelTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TWLogEyeServiceServer).GetOTelTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TWLogEyeService_GetOTelTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TWLogEyeServiceServer).GetOTelTrace(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TWLogEyeService_ServiceDesc is the grpc.ServiceDesc for TWLogEyeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TWLogEyeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "twlogeye.TWLogEyeService",
	HandlerType: (*TWLogEyeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stop",
			Handler:    _TWLogEyeService_Stop_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _TWLogEyeService_Reload_Handler,
		},
		{
			MethodName: "ClearDB",
			Handler:    _TWLogEyeService_ClearDB_Handler,
		},
		{
			MethodName: "GetLastSyslogReport",
			Handler:    _TWLogEyeService_GetLastSyslogReport_Handler,
		},
		{
			MethodName: "GetLastTrapReport",
			Handler:    _TWLogEyeService_GetLastTrapReport_Handler,
		},
		{
			MethodName: "GetLastNetflowReport",
			Handler:    _TWLogEyeService_GetLastNetflowReport_Handler,
		},
		{
			MethodName: "GetLastWindowsEventReport",
			Handler:    _TWLogEyeService_GetLastWindowsEventReport_Handler,
		},
		{
			MethodName: "GetLastOTelReport",
			Handler:    _TWLogEyeService_GetLastOTelReport_Handler,
		},
		{
			MethodName: "GetLastAnomalyReport",
			Handler:    _TWLogEyeService_GetLastAnomalyReport_Handler,
		},
		{
			MethodName: "GetLastMonitorReport",
			Handler:    _TWLogEyeService_GetLastMonitorReport_Handler,
		},
		{
			MethodName: "GetOTelMetric",
			Handler:    _TWLogEyeService_GetOTelMetric_Handler,
		},
		{
			MethodName: "GetOTelTrace",
			Handler:    _TWLogEyeService_GetOTelTrace_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchNotify",
			Handler:       _TWLogEyeService_WatchNotify_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchNotify",
			Handler:       _TWLogEyeService_SearchNotify_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchLog",
			Handler:       _TWLogEyeService_SearchLog_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetSyslogReport",
			Handler:       _TWLogEyeService_GetSyslogReport_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTrapReport",
			Handler:       _TWLogEyeService_GetTrapReport_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetNetflowReport",
			Handler:       _TWLogEyeService_GetNetflowReport_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetWindowsEventReport",
			Handler:       _TWLogEyeService_GetWindowsEventReport_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetOTelReport",
			Handler:       _TWLogEyeService_GetOTelReport_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAnomalyReport",
			Handler:       _TWLogEyeService_GetAnomalyReport_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetMonitorReport",
			Handler:       _TWLogEyeService_GetMonitorReport_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetOTelMetricList",
			Handler:       _TWLogEyeService_GetOTelMetricList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetOTelTraceList",
			Handler:       _TWLogEyeService_GetOTelTraceList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "twlogeye.proto",
}
